export const T_USERS        =   "hf_users"
export const T_MOVIE        =   "hf_movies"
export const T_VIDEO        =   "hf_videos"
export const T_SUBTITLE     =   "hf_subtitles"
export const T_RESET_TOKEN  =   "hf_reset_tokens"
export const T_PAYMENT      =   "hf_payments"
export const T_REVIEWS      =   "hf_movie_reviews"
export const T_SCREENSHOTS  =   "hf_screenshots"
